### ISSUE TITLE
May I ask how you load this package in Xcode?

### ISSUE THREAD

**Issue by eonist** [google/swift-structural#8]
I only get:  The package product 'swift-structural' cannot be used as a dependency of this target because it uses unsafe build flags.

**Comment by shabalind** [comment]
Hi @eonist, at the moment this repo is meant for the hands-on exploration of [the corresponding proposal posted on Swift Forums](https://forums.swift.org/t/automatic-requirement-satisfaction-in-plain-swift/37158). If you would like to play around with it, we recommend to clone the repo and do experiments inside your own fork. We don't really encourage people depending on the project as a library dependency because the API is unstable and might change significantly as the result of Swift Evolution discussions.

If you absolutely have to use it as a dependency you can clone the project and remove [the unsafe flags](https://github.com/google/swift-structural/blob/master/Package.swift#L19) from our package definition. We currently need those flags for benchmarking purposes.
